//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thing1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubMembership
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int ClubId { get; set; }
        public int MembershipOptionId { get; set; }
        public int RoleId { get; set; }
        public System.DateTime TermDate { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string Description { get; set; }
        public bool HasAccessToFinance { get; set; }
        public bool CanEditClubData { get; set; }
        public Nullable<bool> Violation { get; set; }
        public Nullable<bool> IsCurrentOfficer { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Club Club { get; set; }
        public virtual MembershipOption MembershipOption { get; set; }
        public virtual TypesOfRole TypesOfRole { get; set; }
    }
}
