//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thing1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Club()
        {
            this.ClubMemberships = new HashSet<ClubMembership>();
            this.Emails = new HashSet<Email>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int typeId { get; set; }
        public string nickname { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string email_template { get; set; }
        public Nullable<decimal> one_year_fee { get; set; }
        public Nullable<decimal> two_year_fee { get; set; }
        public Nullable<decimal> three_year_fee { get; set; }
        public Nullable<decimal> other_fee_1 { get; set; }
        public Nullable<decimal> other_fee_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubMembership> ClubMemberships { get; set; }
        public virtual TypesOfClub TypesOfClub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Emails { get; set; }
    }
}
