//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thing1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Email()
        {
            this.Recipients = new HashSet<Recipient>();
        }
    
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public System.DateTime Sent { get; set; }
        public string SentBy { get; set; }
        public int ClubId { get; set; }
        public string hiiii { get; set; }
        public string byeee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipient> Recipients { get; set; }
        public virtual Club Club { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
