//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thing1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.ClubEvents = new HashSet<ClubEvent>();
        }
    
        public string Title { get; set; }
        public string Location { get; set; }
        public int Id { get; set; }
        public string Description { get; set; }
        public string TargetAudience { get; set; }
        public int IsPublic { get; set; }
        public string Food { get; set; }
        public string Contact { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime StartsAt { get; set; }
        public System.DateTime EndsAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubEvent> ClubEvents { get; set; }
    }
}
