//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Thing1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MembershipOption()
        {
            this.ClubMemberships = new HashSet<ClubMembership>();
        }
    
        public int Id { get; set; }
        public int ClubId { get; set; }
        public int TypeId { get; set; }
        public int Duration { get; set; }

        [DataType(DataType.Date)]
        public DateTime ExpDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:C0}")]
        public decimal Price { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubMembership> ClubMemberships { get; set; }
        public virtual Club Club { get; set; }
        public virtual TypesOfMembershipOption TypesOfMembershipOption { get; set; }
    }
}
