//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thing1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int TransactionId { get; set; }
        public Nullable<System.DateTime> payment_time { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> clubID { get; set; }
        public string payment_type { get; set; }
        public Nullable<decimal> payment_duration { get; set; }
        public string userID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Club Club { get; set; }
    }
}
