//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thing1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        public int Id { get; set; }
        public int EmailId { get; set; }
        public int TypeId { get; set; }
        public string UserId { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual Recipient Recipients1 { get; set; }
        public virtual Recipient Recipient1 { get; set; }
        public virtual TypesOfRecipient TypesOfRecipient { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
